name: Upload Library to Maven Central

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Decode and save GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private_key.gpg
          gpg --import --batch private_key.gpg

      - name: Update gradle.properties
        run: |
          echo "" >> gradle.properties
          echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> gradle.properties
          echo "signing.password=${{ secrets.SIGNING_PASSWORD }}" >> gradle.properties
          echo "signing.secretKeyRingFile=$(pwd)/private_key.gpg" >> gradle.properties
          echo "mavenCentralUsername=${{ secrets.MAVEN_USERNAME }}" >> gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_PASSWORD }}" >> gradle.properties

      - name: Publish to Maven Central
        run: ./gradlew publish --no-configuration-cache

      - name: Clean up GPG key
        if: always()
        run: rm -f private_key.gpg